# Site Variables
url: https://iamalexbrady.github.io

# Custom settings (GitHub Pages starter)
custom_settings:
  # required
  is_development: false

  # optional/convenience
  name: abcim
  description: The alex brady Course in Miracles

# Handling / Reading
safe: true
include:
  - _pages

keep_files:
  - assets # generate by gulp

exclude:
  - _data/rev-manifest.json
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock

# Conversion
markdown: kramdown

# Output
permalink: pretty
timezone: Europe/Stockholm

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false

# Collections
collections:
  acim_qnas:
    output: true
    sort_by: path
    permalink: /acim/question/:name:output_ext